import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LogoutButton from "@/components/LogoutButton";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-slate-950 text-slate-100">
        <div className="min-h-screen flex">
          <aside className="w-64 bg-[#120738] border-r border-purple-800/60 p-6">
            <div className="mb-8">
              <h2 className="text-xl font-bold tracking-wider text-purple-200">ITMate</h2>
              <p className="text-xs text-purple-300 mt-1">Панель управления</p>
            </div>
            <nav className="space-y-2">
              <a href="/profile" className="flex items-center gap-3 px-3 py-2 rounded-lg bg-purple-800/30 text-purple-100 hover:bg-purple-700/40 transition">
                <span>👤</span>
                <span>Профиль</span>
              </a>
              <LogoutButton />
              <a href="/chats" className="flex items-center gap-3 px-3 py-2 rounded-lg text-purple-100 hover:bg-purple-700/40 transition">
                <span>💬</span>
                <span>Чат</span>
              </a>
              <a href="/goals" className="flex items-center gap-3 px-3 py-2 rounded-lg text-purple-100 hover:bg-purple-700/40 transition">
                <span>🎯</span>
                <span>Создать цель</span>
              </a>
              <a href="/reports" className="flex items-center gap-3 px-3 py-2 rounded-lg text-purple-100 hover:bg-purple-700/40 transition">
                <span>📝</span>
                <span>Написать отчет</span>
              </a>
              <a href="/find_partner" className="flex items-center gap-3 px-3 py-2 rounded-lg text-purple-100 hover:bg-purple-700/40 transition">
                <span>🔍</span>
                <span>Найти партнера</span>
              </a>
            </nav>
          </aside>

          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
